---
  defaultBaseImageVersion: latest
  properties:
  - name: API_KEY
    value: ${API_KEY}
    type: secure
  - name: PROD_CLUSTER_NAME
    value: ${PROD_CLUSTER_NAME}
    type: text
  - name: PROD_REGION_ID
    value: ${PROD_REGION_ID}
    type: text
  stages:
  - name: FETCH
    inputs:
    - type: git
      branch: master
      service: ${GIT_REPO}    
    triggers:
    - type: commit
    properties:
    - name: IMAGE_NAME
      value: ${APP_NAME}
      type: text
    jobs:
    - name: Fetch code
      type: builder
      artifact_dir: ''
      build_type: shell
      script: |+
        #!/bin/bash
        set -x
  
        # Git repo cloned at $WORKING_DIR, copy into $ARCHIVE_DIR
        mkdir -p $ARCHIVE_DIR
        cp -R -n ./ $ARCHIVE_DIR/ || true
  
        # Record git info
        echo "GIT_URL=${GIT_URL}" >> $ARCHIVE_DIR/build.properties
        echo "GIT_BRANCH=${GIT_BRANCH}" >> $ARCHIVE_DIR/# build.properties
        echo "GIT_COMMIT=${GIT_COMMIT}" >> $ARCHIVE_DIR/build.properties
        echo "SOURCE_BUILD_NUMBER=${BUILD_NUMBER}" >> $ARCHIVE_DIR/build.properties
        cat $ARCHIVE_DIR/build.properties
  
  - name: DEPLOY_SERVICES
    properties:
    - name: buildprops
      value: build.properties
      type: file
    - name: MY_REGISTRY_URL
      value: ${REGISTRY_URL}
      type: text
    - name: REGISTRY_NAMESPACE
      value: ${REGISTRY_NAMESPACE}
      type: text
    inputs:
    - type: job
      stage: FETCH
      job: Fetch code
    triggers:
    - type: stage
    jobs:    
    - name: Build java authors and save in IBM Cloud Container Registry
      type: builder
      build_type: cr
      artifact_dir: .
      target:
        region_id: ${REGISTRY_REGION_ID}
        api_key: ${API_KEY}
      namespace: ${REGISTRY_NAMESPACE}
      image_name: ${APP_NAME}
      script: |
        #!/bin/bash    
        echo /------------------------------------
        echo Verify folders, variables in the deployer image
        echo /------------------------------------
        ls
        pwd
        root_folder=$(cd $(dirname $0);pwd)
        cd ${root_folder}/authors-java-jee/
        MY_REGISTRY_URL=${REGISTRY_URL}
        
        echo /------------------------------------*
        echo Root folder: ${root_folder}/authors-java-jee/
        echo Cloud Registry URL: $MY_REGISTRY_URL
        echo Cloud Registry Namespace: $REGISTRY_NAMESPACE 
        echo /------------------------------------
        echo 
        echo /------------------------------------
        echo Build the image and upload the IBM Cloud registry
        echo /------------------------------------
        
        ibmcloud cr image-rm $REGISTRY_URL/$REGISTRY_NAMESPACE/authors:1 || true
        ibmcloud cr build -f ${root_folder}/authors-java-jee/Dockerfile --tag $REGISTRY_URL/$REGISTRY_NAMESPACE/authors:1 .

    - name: Deploy java authors microservice to the Kubernetes cluster
      type: deployer
      build_type: kubernetes
      target:
        region_id: ${PROD_REGION_ID}
        api_key: ${API_KEY}
        kubernetes_cluster: ${PROD_CLUSTER_NAME}
      script: |+
        #!/bin/bash

        echo /------------------------------------
        echo Verify folders, variables in the deployer image
        echo /------------------------------------
        
        ls
        pwd
        root_folder=$(cd $(dirname $0);pwd)
        MY_REGISTRY_URL=${REGISTRY_URL}

        echo /------------------------------------
        echo Root folder: ${root_folder}/authors-java-jee/
        echo Cloud Registry URL: $MY_REGISTRY_URL
        echo Cloud Registry Namespace: $REGISTRY_NAMESPACE 
        echo /------------------------------------
        echo 
        echo /------------------------------------
        echo Create customized IKS-pipeline-deployment.yaml file
        echo /------------------------------------
        
        cd ${root_folder}/authors-java-jee/deployment/
        pwd

        kubectl create ns toolchain-one-service-workshop || true
        kubectl config set-context --current --namespace=toolchain-one-service-workshop

        kubectl delete -f IKS-pipeline-deployment.yaml --ignore-not-found

        sed "s+authors:1+$MY_REGISTRY_URL/$REGISTRY_NAMESPACE/authors:1+g" deployment.yaml.template > IKS-pipeline-deployment.yaml

        kubectl apply -f IKS-pipeline-deployment.yaml
      
        echo //*************************************
        echo Get ClusteIP and NodePort to access the authors microservice from the internet
        echo //*************************************

        nodeport=$(kubectl get svc authors --ignore-not-found --output 'jsonpath={.spec.ports[*].nodePort}')
        clusterip=$(ibmcloud ks workers --cluster $PROD_CLUSTER_NAME | awk '/Ready/ {print $2;exit;}')

        echo //*************************************
        echo Sample API call: \"curl 'http://${clusterip}:${nodeport}/api/v1/getauthor?name=Niklas%20Heidloff'\"
        echo //*************************************
  